export const VISA_STATUS_FLOW = {
  NOT_STARTED: ["DOCUMENTS_IN_PROGRESS"],
  DOCUMENTS_IN_PROGRESS: ["APPOINTMENT_BOOKED"],
  APPOINTMENT_BOOKED: ["SUBMITTED"],
  SUBMITTED: ["UNDER_REVIEW"],
  UNDER_REVIEW: ["APPROVED", "REJECTED"],
  APPROVED: [],
  REJECTED: [],
  CANCELLED: [],
};
